LINK_MAIN = "https://videocdn.tv/api/"

TRANSLATIONS = LINK_MAIN + "translations"
MOVIES = LINK_MAIN + "movies"
ANIMES = LINK_MAIN + "animes"
TV_SERIES = LINK_MAIN + "tv-series"
TV_SERIES_SEASONS = LINK_MAIN + "tv-series/seasons"
TV_SERIES_EPISODES = LINK_MAIN + "tv-series/episodes"
ANIME_TV_SERIES = LINK_MAIN + "anime-tv-series"
ANIME_TV_SERIES_SEASONS = LINK_MAIN + "anime-tv-series/seasons"
ANIME_TV_SERIES_EPISODES = LINK_MAIN + "anime-tv-series/episodes"
SHOW_TV_SERIES = LINK_MAIN + "show-tv-series"
SHOW_TV_SERIES_SEASONS = LINK_MAIN + "show-tv-series/seasons"
SHOW_TV_SERIES_EPISODES = LINK_MAIN + "show-tv-series/episodes"
